### ISSUE TITLE
Compilation failure (mistralrs-paged-attn v0.1.26)

### ISSUE THREAD

**Issue by MoonRide303** [EricLBuehler/mistral.rs#569]
**Describe the bug**
Trying to build current master with `cargo build --release --features cuda` results in compilation failure:
```
error: failed to run custom build command for `mistralrs-paged-attn v0.1.26 (D:\repos-git\mistral.rs\mistralrs-paged-attn)`

Caused by:
  process didn't exit successfully: `D:\repos-git\mistral.rs\target\release\build\mistralrs-paged-attn-fed31e2777b0bce3\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-changed=build.rs
  cargo:rerun-if-changed=src/pagedattention.cu
  cargo:rerun-if-changed=src/copy_blocks_kernel.cu
  cargo:rerun-if-changed=src/reshape_and_cache_kernel.cu
  cargo:info=["/usr", "/usr/local/cuda", "/opt/cuda", "/usr/lib/cuda", "C:/Program Files/NVIDIA GPU Computing Toolkit", "C:/CUDA"]
  cargo:rerun-if-env-changed=CUDA_COMPUTE_CAP
  cargo:rustc-env=CUDA_COMPUTE_CAP=89
  cargo:info=Builder { cuda_root: Some("C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.5"), kernel_paths: ["src\\copy_blocks_kernel.cu", "src\\pagedattention.cu", "src\\reshape_and_cache_kernel.cu"], watch: [], include_paths: ["src\\attention\\attention_generic.cuh", "src\\attention\\attention_utils.cuh", "src\\attention\\dtype_bfloat16.cuh", "src\\attention\\dtype_float16.cuh", "src\\attention\\dtype_float32.cuh"], compute_cap: Some(89), out_dir: "D:\\repos-git\\mistral.rs\\target\\release\\build\\mistralrs-paged-attn-3417811eaef6576e\\out", extra_args: [] }
  copy_blocks_kernel.cu
  tmpxft_00006fe4_00000000-10_copy_blocks_kernel.cudafe1.cpp
  reshape_and_cache_kernel.cu
  tmpxft_00006da0_00000000-10_reshape_and_cache_kernel.cudafe1.cpp
  pagedattention.cu
  tmpxft_00008320_00000000-10_pagedattention.cudafe1.cpp
  D:\repos-git\mistral.rs\mistralrs-paged-attn\src\pagedattention.cu(85): error C2146: syntax error: missing ')' before identifier 'exp_sums'
  D:\repos-git\mistral.rs\mistralrs-paged-attn\src\pagedattention.cu(85): error C3646: 'exp_sums': unknown override specifier
  D:\repos-git\mistral.rs\mistralrs-paged-attn\src\pagedattention.cu(85): error C2988: unrecognizable template declaration/definition
  D:\repos-git\mistral.rs\mistralrs-paged-attn\src\pagedattention.cu(85): error C2059: syntax error: ','
  D:\repos-git\mistral.rs\mistralrs-paged-attn\src\pagedattention.cu(99): error C2059: syntax error: ')'
  D:\repos-git\mistral.rs\mistralrs-paged-attn\src\pagedattention.cu(99): error C2143: syntax error: missing ';' before '{'
  D:\repos-git\mistral.rs\mistralrs-paged-attn\src\pagedattention.cu(99): error C2447: '{': missing function header (old-style formal list?)
  D:\repos-git\mistral.rs\mistralrs-paged-attn\src\pagedattention.cu(161): warning C4068: unknown pragma 'unroll'
  D:\repos-git\mistral.rs\mistralrs-paged-attn\src\pagedattention.cu(201): warning C4068: unknown pragma 'unroll'
  D:\repos-git\mistral.rs\mistralrs-paged-attn\src\pagedattention.cu(232): warning C4068: unknown pragma 'unroll'
  D:\repos-git\mistral.rs\mistralrs-paged-attn\src\pagedattention.cu(244): warning C4068: unknown pragma 'unroll'
  D:\repos-git\mistral.rs\mistralrs-paged-attn\src\pagedattention.cu(291): warning C4068: unknown pragma 'unroll'
  D:\repos-git\mistral.rs\mistralrs-paged-attn\src\pagedattention.cu(310): warning C4068: unknown pragma 'unroll'
  D:\repos-git\mistral.rs\mistralrs-paged-attn\src\pagedattention.cu(321): warning C4068: unknown pragma 'unroll'
  D:\repos-git\mistral.rs\mistralrs-paged-attn\src\pagedattention.cu(332): warning C4068: unknown pragma 'unroll'
  D:\repos-git\mistral.rs\mistralrs-paged-attn\src\pagedattention.cu(335): warning C4068: unknown pragma 'unroll'
  D:\repos-git\mistral.rs\mistralrs-paged-attn\src\pagedattention.cu(348): warning C4068: unknown pragma 'unroll'
  D:\repos-git\mistral.rs\mistralrs-paged-attn\src\pagedattention.cu(354): warning C4068: unknown pragma 'unroll'
  D:\repos-git\mistral.rs\mistralrs-paged-attn\src\pagedattention.cu(367): warning C4068: unknown pragma 'unroll'
  D:\repos-git\mistral.rs\mistralrs-paged-attn\src\pagedattention.cu(383): warning C4068: unknown pragma 'unroll'

  --- stderr
  thread '<unnamed>' panicked at C:\Users\[REDACTED]\.cargo\git\checkouts\bindgen_cuda-caa0d404b435df9d\fb7ed75\src\lib.rs:262:21:
  nvcc error while executing compiling: "nvcc" "--gpu-architecture=sm_89" "-c" "-o" "D:\\repos-git\\mistral.rs\\target\\release\\build\\mistralrs-paged-attn-3417811eaef6576e\\out\\pagedattention-7ea3e25b70ea4db9.o" "--default-stream" "per-thread" "src\\pagedattention.cu"

  # stdout


  # stderr

  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```

**Latest commit**
990b4273a19fe94acd946b40c1202375f0fbca27

**Comment by EricLBuehler** [comment]
Thanks for reporting this - it builds fine on my system so it may be a compiler version issue.

Can you please let me know:
```
nvcc --version
```
```
nvidia-smi
```

**Comment by MoonRide303** [comment]
```
nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Thu_Jun__6_03:03:05_Pacific_Daylight_Time_2024
Cuda compilation tools, release 12.5, V12.5.82
Build cuda_12.5.r12.5/compiler.34385749_0
```
```
nvidia-smi
Sat Jul 13 00:35:39 2024
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 555.99                 Driver Version: 555.99         CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4080      WDDM  |   00000000:01:00.0  On |                  N/A |
|  0%   41C    P8             22W /  320W |   15257MiB /  16376MiB |      5%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
```

**Comment by vitorfdl** [comment]
I'm having exactly same problem trying to compile for windows 11 x64

```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Thu_Jun__6_03:03:05_Pacific_Daylight_Time_2024
Cuda compilation tools, release 12.5, V12.5.82
Build cuda_12.5.r12.5/compiler.34385749_0
```


```
Sat Jul 13 05:44:16 2024
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 556.12                 Driver Version: 556.12         CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4070 ...  WDDM  |   00000000:01:00.0  On |                  N/A |
|  0%   33C    P8             10W /  285W |    2402MiB /  16376MiB |      5%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
```

**Comment by MoonRide303** [comment]
> Hmm, this is super strange. Can you please try to run `pip install vllm` and see what happens? They use the same kernels.

vLLM seems to be only for Linux users:
```
pip install vllm
Collecting vllm
  Downloading vllm-0.5.1.tar.gz (790 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 790.6/790.6 kB 3.8 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      Traceback (most recent call last):
        File "D:\anaconda3\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "D:\anaconda3\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "D:\anaconda3\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\[REDACTED]\AppData\Local\Temp\pip-build-env-fa9idr7f\overlay\Lib\site-packages\setuptools\build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "C:\Users\[REDACTED]\AppData\Local\Temp\pip-build-env-fa9idr7f\overlay\Lib\site-packages\setuptools\build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "C:\Users\[REDACTED]\AppData\Local\Temp\pip-build-env-fa9idr7f\overlay\Lib\site-packages\setuptools\build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 36, in <module>
      AssertionError: vLLM only supports Linux platform (including WSL).
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by EricLBuehler** [comment]
I just merged #578 which updates some of the `cudarc` dep stuff, it probably will not resolve the issue here though. #577 just disables PagedAttention for Windows machines but I have not merged it as I am not confident in that it is necessary.

**Comment by MoonRide303** [comment]
> I just merged #578 which updates some of the `cudarc` dep stuff, it probably will not resolve the issue here though. #577 just disables PagedAttention for Windows machines but I have not merged it as I am not confident in that it is necessary.

Same error as of 990774fa80c1c9455d3d7bf9cf8305791a1939d3 for me.

**Comment by EricLBuehler** [comment]
@MoonRide303 fixed in #577

**Comment by MoonRide303** [comment]
@EricLBuehler It still doesn't compile - the same error I previously got on handle_windows_paged_attn branch (#577) happens now on master (tested on e3208e5b3aca4ce1daee8073887b6324cedf45cb):
```
error: couldn't read `D:\repos-git\mistral.rs\target\release\build\mistralrs-paged-attn-66c505a4a62e5607\out/copy_blocks_kernel.ptx`: Nie można odnaleźć określonego pliku. (os error 2)
 --> mistralrs-paged-attn\src\lib.rs:3:5
  |
3 |     include_str!(concat!(env!("OUT_DIR"), "/copy_blocks_kernel.ptx"));
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: this error originates in the macro `include_str` (in Nightly builds, run with -Z macro-backtrace for more info)

error: couldn't read `D:\repos-git\mistral.rs\target\release\build\mistralrs-paged-attn-66c505a4a62e5607\out/pagedattention.ptx`: Nie można odnaleźć określonego pliku. (os error 2)
 --> mistralrs-paged-attn\src\lib.rs:5:34
  |
5 | pub const PAGEDATTENTION: &str = include_str!(concat!(env!("OUT_DIR"), "/pagedattention.ptx"));
  |                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: this error originates in the macro `include_str` (in Nightly builds, run with -Z macro-backtrace for more info)

error: couldn't read `D:\repos-git\mistral.rs\target\release\build\mistralrs-paged-attn-66c505a4a62e5607\out/reshape_and_cache_kernel.ptx`: Nie można odnaleźć określonego pliku. (os error 2)
 --> mistralrs-paged-attn\src\lib.rs:8:5
  |
8 |     include_str!(concat!(env!("OUT_DIR"), "/reshape_and_cache_kernel.ptx"));
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: this error originates in the macro `include_str` (in Nightly builds, run with -Z macro-backtrace for more info)

error: could not compile `mistralrs-paged-attn` (lib) due to 3 previous errors
warning: build failed, waiting for other jobs to finish...
```

**Comment by EricLBuehler** [comment]
@MoonRide303 thanks fro reporthing this, I'll get it fixed in #588 asap!
