### ISSUE TITLE
Compilation failure (mistralrs-paged-att)

### ISSUE THREAD

**Issue by vitorfdl** [EricLBuehler/mistral.rs#588]
**Describe the bug**
Trying to build current master with `cargo build --release --features "cuda flash-attn"` results in compilation failure:
![image](https://github.com/user-attachments/assets/a82feab3-0762-44f9-b1e9-852715bdac11)

That's my second attempt to build, where the first attempt failed because of [#569](https://github.com/EricLBuehler/mistral.rs/issues/569)

SO: Windows 11 x64
Terminal: Powershell
Cuda Toolkit: 12.5

**Latest commit**
[ba40a2b](https://github.com/EricLBuehler/mistral.rs/commit/ba40a2be614c522d0633a1e303568001cb1bc617)

**Comment by EricLBuehler** [comment]
@vitorfdl I think #589 should resolve this, can you please confirm with:
```
git pull
git switch windows_pa_build_fix
```
And then rebuild?

**Comment by vitorfdl** [comment]
```
cargo build --release --features "cuda"                                                                          pwsh  20:38:39 
   Compiling mistralrs-pyo3 v0.1.26 (C:\ai-models\mistral.rs\mistralrs-pyo3)
   Compiling mistralrs-bench v0.1.26 (C:\ai-models\mistral.rs\mistralrs-bench)
   Compiling mistralrs-server v0.1.26 (C:\ai-models\mistral.rs\mistralrs-server)
error: linking with `link.exe` failed: exit code: 1181
error: could not compile `mistralrs-bench` (bin "mistralrs-bench") due to 1 previous error
warning: build failed, waiting for other jobs to finish...
error: linking with `link.exe` failed: exit code: 1181
error: could not compile `mistralrs-pyo3` (lib) due to 1 previous error
error: linking with `link.exe` failed: exit code: 1181
error: could not compile `mistralrs-server` (bin "mistralrs-server") due to 1 previous error
````

The changes seems to have fixed the problems that were popping up previously. But now there is this new error when trying to compile with CUDA.

**Comment by EricLBuehler** [comment]
Yeah, that makes sense. If it is compiling `mistralrs-server`, it compiled `mistralrs-core` so the CUDA compilation errors should be gone.

**Comment by vitorfdl** [comment]
Yeah, usually when I got linking issues is on a lib that I just need to install.

In this case, the error is    = note: LINK : fatal error LNK1181: cannot open input file 'mistralcuda.lib'
So I'm unsure if I can fix that myself.

**Comment by EricLBuehler** [comment]
@vitorfdl I just opened #591 which should fix this, can you please run:

```
git pull
git switch cuda_kernels_build_windows
```

**Comment by vitorfdl** [comment]
![image](https://github.com/user-attachments/assets/0d8df692-c5c1-4ac8-8d5c-6f542b1a29e5)

Building with cuda seems fixed. Now as for the flash-attn, I'm still getting errors:
```
--- stderr
 vitorfdl    mistral.rs   cuda_kernels_build_window ≡  1  44.394s⠀   cargo build --release --features "cuda flash-attn"                                                       pwsh  04:44:07 
   Compiling candle-flash-attn v0.6.0 (https://github.com/EricLBuehler/candle.git?rev=c967be9#c967be9c)
   Compiling mistralrs-core v0.1.26 (C:\ai-models\mistral.rs\mistralrs-core)
error: failed to run custom build command for `candle-flash-attn v0.6.0 (https://github.com/EricLBuehler/candle.git?rev=c967be9#c967be9c)`

Caused by:
  process didn't exit successfully: `C:\ai-models\mistral.rs\target\release\build\candle-flash-attn-a145d740d88eab38\build-script-build` (exit code: 101)
    --- stdout
    (...)
  flash_fwd_hdim32_bf16_sm80.cu
  flash_fwd_hdim96_fp16_sm80.cu
  flash_fwd_hdim128_fp16_sm80.cu
  flash_fwd_hdim160_bf16_sm80.cu
  flash_fwd_hdim224_fp16_sm80.cu
  flash_fwd_hdim160_fp16_sm80.cu
  flash_fwd_hdim224_bf16_sm80.cu
  flash_api.cu
  thread '<unnamed>' panicked at C:\Users\vitorfdl\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bindgen_cuda-0.1.5\src\lib.rs:262:21:
  nvcc error while executing compiling: "nvcc" "--gpu-architecture=sm_89" "-c" "-o" "C:\\ai-models\\mistral.rs\\target\\release\\build\\candle-flash-attn-b7579997ed1ea5c6\\out\\flash_fwd_hdim128_fp16_sm80-759fdfecd1f0ed1c.o" "--default-stream" "per-thread" "-std=c++17" "-O3" "-U__CUDA_NO_HALF_OPERATORS__" "-U__CUDA_NO_HALF_CONVERSIONS__" "-U__CUDA_NO_HALF2_OPERATORS__" "-U__CUDA_NO_BFLOAT16_CONVERSIONS__" "-Icutlass/include" "--expt-relaxed-constexpr" "--expt-extended-lambda" "--use_fast_math" "--verbose" "kernels/flash_fwd_hdim128_fp16_sm80.cu"
````

**Comment by EricLBuehler** [comment]
@vitorfdl can you please put the error in a GH Gist?

**Comment by vitorfdl** [comment]
<script src="https://gist.github.com/vitorfdl/8e1a9a8cf3da2f5e40f62162cb039a8c.js"></script>

**Comment by EricLBuehler** [comment]
@vitorfdl looks like Flash attention V2 is not compatible with Cutlass V3 on Windows (refs Dao-AILab/flash-attention/#345, [docs](https://github.com/NVIDIA/cutlass#operating-systems)). I think if you compile without this it should be fine!

**Comment by vitorfdl** [comment]
> @vitorfdl looks like Flash attention V2 is not compatible with Cutlass V3 on Windows (refs Dao-AILab/flash-attention/#345, [docs](https://github.com/NVIDIA/cutlass#operating-systems)). I think if you compile without this it should be fine!

You mean, compiling without the -fa parameter?

**Comment by EricLBuehler** [comment]
Yes, without `--features flash-attn` should work

**Comment by vitorfdl** [comment]
Yeah, I've confirmed in [earlier comments](https://github.com/EricLBuehler/mistral.rs/issues/588#issuecomment-2238578960) that building with cuda only works fine.

But then I lost the flash-attn feature right? I've compiled llamacpp and it does make a lot difference in speeds to have flash attention working.

Nonetheless, I think the issues are fixed as I can now compile mistralrs

**Comment by EricLBuehler** [comment]
@vitorfdl closing as there have been no comments for a bit. Please feel free to reopen.
